# Generated by Django 4.2 on 2023-07-17 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='role',
        ),
        migrations.AddField(
            model_name='info',
            name='cases',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='info',
            name='date_update',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='info',
            name='deaths',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='info',
            name='test_completed',
            field=models.IntegerField(default=1),
        ),
    ]
