# Generated by Django 4.2 on 2023-07-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_info_full_name_remove_info_role_info_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='country_name',
            field=models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('MB', 'Mozambique'), ('SA', 'South Africa'), ('NI', 'Niger'), ('TG', 'Togo'), ('ZA', 'Zambia'), ('BN', 'Benin Republic'), ('CM', 'Cameroun'), ('BT', 'Botswana'), ('MA', 'Mali'), ('ZI', 'Zimbabwe'), ('AN', 'Angola')], default='unknown', max_length=50),
        ),
    ]
